[env]
CC_x86_64-unknown-linux-musl = "gcc"

[build]
#target = ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]

[target.x86_64-unknown-linux-musl]
#linker = "rust-lld"


[target.x86_64-pc-windows-msvc]
#linker = "rust-lld"

#fn main() {
#println!("cargo:rerun-if-changed=build.rs");
#println!("cargo:rerun-if-changed=dynamiclist");
#
#}